# ==============================================================================
# Métadonnées pour le Rôle MinIO
# ==============================================================================
# Ce fichier contient les métadonnées du rôle, telles que l'auteur,
# la description, la licence et les dépendances.
# ==============================================================================
galaxy_info:
  author: "Jules"
  description: "Rôle Ansible pour installer et configurer MinIO."
  license: "MIT"
  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - bionic

  galaxy_tags:
    - minio
    - s3
    - storage
    - object

dependencies: []