# Playbook pour déployer Rundeck et ses dépendances (Java, MySQL).

---
- name: "Installer Rundeck et ses dépendances"
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: java
    - role: mysql
    - role: rundeck
    - role: nginx
